### ISSUE TITLE
It doesn't work. (Entity ID Problem)

### ISSUE THREAD

**Issue by GoodLucky777** [PetteriM1/Scale#1]
I think Entity IDs are int but this plugin use a float. Can you fix it?

**Comment by PetteriM1** [comment]
> I think Entity IDs are int but this plugin use a float. Can you fix it?

Actually the entity id is a long. Looks like I have messed it up with the scale which is a float. The plugin should still work normally though.

**Comment by GoodLucky777** [comment]
i use command like
/scale 3.0 11.0
but it says entity cannot be found. Is cow entity ID is 11.0?

**Comment by PetteriM1** [comment]
Entity id is not the same as the network id. It's different every time so use /geteid to see it. Also don't put .0 as it's not a float.

**Comment by GoodLucky777** [comment]
thank you!
